export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

plugins=(git docker npm node rust)

source "$ZSH/oh-my-zsh.sh"

if [ -f "$HOME/.config/holospaces-aliases.zsh" ]; then
  source "$HOME/.config/holospaces-aliases.zsh"
fi

export EDITOR="${EDITOR:-vim}"
export PAGER="${PAGER:-less}"
